//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenCrudMVC_NFramework1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public string nombreEmpleado { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Departamento IdDepartamentoNavigation { get; set; }
    }
}
